[battery]
full_symbol = "âš¡ï¸"
charging_symbol = "ğŸ”Œ "
unknown_symbol = "â™»: "
empty_symbol = "â—"
discharging_symbol = "ğŸ”‹ "

[[battery.display]]
threshold = 100
style = "bold white"

[cmd_duration]
min_time = 500
format = "underwent [$duration](bold yellow)"

[character]
# success_symbol = "[ âœ… ](bold green) "
# error_symbol = "[ ğŸš« ](bold red) "
# vicmd_symbol = "[V](bold green) "
# format = "[ â™¥ï¸ ](bold red) "
format = ""

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = '[ âœ”âœ“ ](bold green)'
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[jobs]
symbol = "+ "
number_threshold = 1
symbol_threshold = 0
format = "[$symbol$number]($style) "

[username]
style_user = "red yellow"
format = "[$user]($style):"
disabled = false
show_always = true

[directory]
truncation_length = 1
truncation_symbol = ""
read_only_style = "red"
home_symbol = "ğŸ  "
style = "green bold"

[shell]
zsh_indicator = "ï‘ _"
style = "red bold dimmed"
disabled = false
